name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: guess test
      id: guess-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: guess test
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GUESS-TEST_RESULTS: "${{steps.guess-test.outputs.result}}"
      with:
        runners: guess-test
